config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => "/ckeditor"

  namespace :admin do
    root "dashboards#home"
    resources :categories
    resources :users
    resources :posts, except: %i[new create edit]
  end

  namespace :author do
    resources :posts, except: :destroy
    resources :users, only: %i[show edit update]
    resources :tags, only: :show
  end

  root "static_pages#index"
  resources :tags, only: :show
  resources :categories
  resources :comments, only: %i[create destroy] do
    resources :reactions
  end
  resources :posts, only: %i[index show] do
    resources :reactions, only: %i[create update]
  end
end

app/views/shared/_category.slim
li class="cat-#{category.id}"
  = link_to category.name, category_path(category)

app/views/shared/_error_messages.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains #{pluralize(object.errors.count, "error")}.
    ul
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_footer.slim
footer#footer
  .container
    .row
      .footer-widget
        .footer-logo
          = link_to root_path, class: "logo" do
            - image_tag "news.png"
        .footer-copyright
          span
            | © Website is made by Ghun
            i.fa.fa-heart-o aria-hidden="true"

app/views/shared/_header.slim
body
  header#header
    #nav
      #nav-fixed
        .container style=("width: auto;")
          .nav-logo
            = link_to root_path, class: "logo" do
              - image_tag "news.png", alt: ""
          ul.nav-menu.nav.navbar-nav style="margin-left: 15px;"
            = render partial: "shared/category", collection: categories_list, as: :category
          .nav-btns
            = render "posts/form_posts_search"
            - if user_signed_in?
              ul.nav.navbar-nav.ml-auto style=("margin-top: -30px; margin-right: 5px; float: right")
                li.nav-item.dropdown
                  .dropdown style="float: right;"
                    button.dropbtn style="display: none;"
                    | Hi, #{first_name(current_user.name)}
                    .dropdown-content
                      = link_to "#" , class: "dropdown-item" do
                        i.fa.fa-user style="margin-right: 22px; color: #597BAB"
                        | Profile
                      = link_to "#", class: "dropdown-item" do
                        i.fa.fa-wrench style="margin-right: 20px; color: #597BAB"
                        | Settings
                      - if current_user.admin?
                        = link_to admin_posts_path, class: "dropdown-item" do
                          i.fas.fa-user-shield style="margin-right: 20px; color: #597BAB"
                          | Admin
                      - if current_user.author?
                        = link_to author_posts_path, class: "dropdown-item" do
                          i.fas.fa-user-edit style="margin-right: 20px; color: #597BAB"
                          | Article
                      = link_to destroy_user_session_path, class: "dropdown-item" , method: :delete do
                        i.fa.fa-lock style="margin-right: 24px; color: #597BAB"
                        | Logout
            - else
              .login style=("margin-top: -29px; margin-right: 20px; float: right")
                = link_to new_user_session_path do
                  i.fas.fa-sign-in-alt
                  |  Login

app/views/shared/_recent_posts.slim
.post.post-widget#post-widget
  = link_to post_path(post), class: "post-img" do
    = image_tag(post.image.url, alt: "")
  .post-body
    h3.post-title
      = link_to post.title, "#"