config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => "/ckeditor"

  namespace :admin do
    root "dashboards#home"
    resources :categories
    resources :users
    resources :posts, except: %i[new create edit]
  end

  namespace :author do
    resources :posts, except: :destroy
    resources :users, only: %i[show edit update]
    resources :tags, only: :show
  end

  root "static_pages#index"
  resources :tags, only: :show
  resources :categories
  resources :comments, only: %i[create destroy] do
    resources :reactions
  end
  resources :posts, only: %i[index show] do
    resources :reactions, only: %i[create update]
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
end

app/controllers/author/tags_controller.rb
# frozen_string_literal: true

module Author
  class TagsController < Author::BasicController
    def show
      @posts = Post.tagged_with params[:id]
    end
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  def show
    @posts = Post.where(active: true).tagged_with(params[:id]).page(params[:page]).per(8)
    @recent_posts = Post.where(active: true).last(8)
    @categories_index = Category.all.includes(:posts).limit(4)
    @tags = Tag.all.last(5)
    most_in_week[0].nil? ? (@most_read_1 = Post.last(4)[0]) : (@most_read_1 = Post.find(most_in_week[0][0]))
    most_in_week[1].nil? ? (@most_read_2 = Post.last(4)[1]) : (@most_read_2 = Post.find(most_in_week[1][0]))
    @most_read_3 = most_in_week[2].nil? ? Post.last(4)[2] : Post.find(most_in_week[2][0])
    @most_read_4 = most_in_week[3].nil? ? Post.last(4)[3] : Post.find(most_in_week[3][0])
    @featured_post_1 = featured_posts[0].nil? ? Post.last(2)[0] : Post.find(featured_posts[0][0])
    @featured_post_2 = featured_posts[1].nil? ? Post.last(2)[1] : Post.find(featured_posts[1][0])
  end
end

app/views/tags/_post.slim
.post.post-row style="margin-bottom: 40px;"
  = link_to post_path(post), class: "post-img" do
    = image_tag(post.image.url, alt: "")
  .post-body
    .post-meta
      = link_to post.category.name, category_path(post.category), class: "post-category cat-#{post.category.id}"
      span.post-date
        = post.updated_at.strftime("%b %d, %Y")
    .post-title
      = link_to post.title, post_path(post), style: "font-size: 20px"
    h5.post-header
      = truncate(post.header, length: 100)
    .aside-widget
      .tags-widget
        .tag style= "width: 50px; float: left; margin-top: -4px;"
            h4
              | Tags :
        .tags
          ul style="margin-left: 50px;"
            - post.tag_list.each do |tag|
              li
                = link_to tag, tag_path(tag)

app/views/tags/show.slim
.section
  .container
    .row
      .col-md-8
        .section-title style="padding-left: 15px;"
          .aside-widget
            .tags-widget
              .tag style= "width: 50px; float: left; margin-top: -4px;"
                h4
                  | Tag :
              .tags
                ul style="margin-left: 50px;"
                  li
                    = link_to params[:id], tag_path(params[:id])
          = render partial: "post", collection: @posts[0..@posts.size], as: :post
        .center style=("text-align: center; width: 50%")
          = paginate @posts, theme: "twitter-bootstrap-3"
      .col-md-4
        = render "static_pages/advertisement"
        h3 Most read
        = render partial: "static_pages/most_read"
        = render "static_pages/featured_posts", post_1: @featured_post_1, post_2: @featured_post_2
        = render "static_pages/categories"
        = render "static_pages/tags", tags: @tags