config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => "/ckeditor"

  namespace :admin do
    root "dashboards#home"
    resources :categories
    resources :users
    resources :posts, except: %i[new create edit]
  end

  namespace :author do
    resources :posts, except: :destroy
    resources :users, only: %i[show edit update]
    resources :tags, only: :show
  end

  root "static_pages#index"
  resources :tags, only: :show
  resources :categories
  resources :comments, only: %i[create destroy] do
    resources :reactions
  end
  resources :posts, only: %i[index show] do
    resources :reactions, only: %i[create update]
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  is_impressionable
  acts_as_taggable

  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :reactions, as: :reactionable

  validates :title, presence: true
  validates :header, presence: true
  validates :content_new, presence: true
  validates :category_id, presence: true

  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  class PostsController < Admin::BaseController
    before_action :load_post, except: :index

    def index
      @posts = Post.all
    end

    def show; end

    def update
      @post.update!(content: @post.content_new, active: true, public: true)
      flash[:success] = "The article updated!"
      redirect_to admin_posts_path
    end

    private

    def load_post
      @post = Post.find params[:id]
    end

    def post_update(post)
      post.content = post.content_new
      post.active = true
      post.public = true
    end
  end
end

app/controllers/author/basic_controller.rb
# frozen_string_literal: true

module Author
  class BasicController < ActionController::Base
    protect_from_forgery with: :exception
    layout "admin"
    before_action :authenticate_user!
    before_action :authorize_author

    def authorize_author
      return if user_signed_in? && current_user.author?

      redirect_to new_user_session_path
      flash[:danger] = "You must login with valid account !"
    end
  end
end

app/controllers/author/posts_controller.rb
# frozen_string_literal: true

module Author
  class PostsController < Author::BasicController
    before_action :load_post, only: %i[edit update show]
    before_action :load_categories, only: %i[new edit]

    def index
      @posts = Post.all.page(params[:page]).per(10)
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new post_params
      if @post.save
        flash[:success] = "The article was create!"
        redirect_to author_posts_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @post.update_attributes post_params
        flash[:info] = "The article was update!"
        redirect_to author_posts_path
      else
        render :edit
      end
    end

    private

    def post_params
      params.require(:post).permit :user_id, :title, :header, :content_new,
                                   :public, :category_id, :image, :tag_list, :video
    end

    def load_post
      @post = Post.find params[:id]
    end

    def load_categories
      @category_options = Category.pluck :name, :id
    end
  end
end

app/controllers/author/tags_controller.rb
# frozen_string_literal: true

module Author
  class TagsController < Author::BasicController
    def show
      @posts = Post.tagged_with params[:id]
    end
  end
end

app/controllers/author/users_controller.rb
# frozen_string_literal: true

module Author
  class UsersController < Author::BasicController
    before_action :find_user, only: %i[show update edit]

    def edit; end

    def update
      if @user.update_attributes(user_params)
        flash[:success] = "Update successfully !"
        redirect_to author_posts_path
      else
        render :edit
      end
    end

    private

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit :name, :birthday, :address, :email, :role,
                                   :password, :password_confirmation
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :load_post, only: :show
  impressionist actions: [:show], unique: %i[impressionable_type impressionable_id session_hash]

  def index
    @posts = Post.where(active: true, public: true)
    @q = Post.where(active: true, public: true).ransack(params[:q])
    @post_results = @q.result(distinct: true).page(params[:page]).per(12)
  end

  def show
    @comments = @post.comments.where(parent_id: nil)
    @comment = @post.comments.build
    @tags = Tag.all.last(5)
    @featured_post_1 = featured_posts[0].nil? ? Post.last(2)[0] : Post.find(featured_posts[0][0])
    @featured_post_2 = featured_posts[1].nil? ? Post.last(2)[1] : Post.find(featured_posts[1][0])
  end

  private

  def load_post
    (@post = Post.find_by_id(params[:id])) || not_found
  end
end

app/views/author/posts/_post_form.slim
.col-md-10.col-md-offset-1
  .card
    .card-header
      strong
        = title
    .card-body
        = form_for [:author, post] do |f|
          = render "shared/error_messages", object: f.object
          = f.hidden_field :user_id, value: 1
          = f.hidden_field :public, value: false
          = f.label :category_id, "Category"
          = f.select :category_id, Category.pluck(:name, :id), {}, class: "form-control"
          br
          = f.label :image
          = f.file_field :image
          br
          = f.label :video
          = f.file_field :video, accept: "video/mp4, video/avi, video/mov, fvideo/flv, video/wmv"
          br
          = f.label :title, "Title"
          = f.text_field :title, class: "form-control"
          br
          = f.label :header, "Header"
          = f.text_area :header, class: "form-control"
          br
          = f.label :tag_list
          = f.text_field :tag_list, class: "form-control"
          br
          = f.label :content_new, "Content"
          = f.text_area :content_new, class: "ckeditor"
          br
          = f.submit button, class: "btn btn-block btn-sm btn-success"

app/views/author/posts/_posts.slim
tr
  td.text-center
    = post.id
  td
    = post.category.name
  td
    = post.title
  td
    - post.tag_list.each do |tag|
      | &ensp;&#35;
      = link_to tag, author_tag_path(tag)
  td.text-center
    = post.impressionist_count
  td.text-center
    - if post.public
      strong.text-success
        i.fas.fa-check
    - else
      strong.text-warning
        i.fas.fa-spinner
  td.text-center
    = link_to edit_author_post_path post
      i.far.fa-edit

app/views/author/posts/edit.slim
= render "post_form", title: "Edit Article", button: "Update Article", post: @post

app/views/author/posts/index.slim
table.table.table-responsive-sm.table-hover.table-outline.mb-0
  thead.thead-light
    tr
      th.text-center #ID
      th Category
      th Headline
      th Tags
      th.text-center Views
      th.text-center Status
      th.text-center Edit
  tbody
  = render partial: "posts", collection: @posts, as: :post
.center style=("text-align: center;")
  = paginate @posts, theme: "twitter-bootstrap-3"

app/views/author/posts/new.slim
= render "post_form", title: "New Article", button: "Create Article", post: @post